config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :plots, only: [:index]
  resources :plant_plots, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
   has_many :plots
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :plant_plots
  has_many :plots, through: :plant_plots
end

app/models/plant_plot.rb
class PlantPlot < ApplicationRecord
  belongs_to :plant
  belongs_to :plot
end

app/models/plant_plots.rb
class PlantPlot < ApplicationRecord
  belongs_to :plant
  belongs_to :plot
end

app/models/plants.rb
class Plant < ApplicationRecord
  has_many :plant_plots
  has_many :plots, through: :plant_plots
end

app/models/plot.rb
class Plot < ApplicationRecord
   belongs_to :garden
   has_many :plant_plots
   has_many :plants, through: :plant_plots
end

app/models/plot_plant.rb
class PlotPlant < ApplicationRecord
  belongs_to :plot
  belongs_to :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plant_plots_controller.rb
class PlantPlotsController < ApplicationController
  def destroy
    plant_plot = PlantPlot.find(params[:id])
    plant = plant_plot.plant
    plant.destroy
    redirect_to plots_path
  end
end

app/controllers/plot_plants_controller.rb
class PlotPlantsController < ApplicationController
  def destroy
    @pp = PlotPlant.find(params[:id])
    @plot = pp.plot
    @pp.destroy
    @redirect to plot_path(plot)
  end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  def index
    @plots = Plot.includes(:plants).all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunityGarden7B2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plots/index.html.erb
<div id="plots">
  <% @plots.each do |plot| %>
    <div id="plot-<%= plot.id %>">
      <p>Plot Number: <%= plot.number %></p>
      <p>Plants:</p>
        <% plot.plants.each do |plant| %>
          <div id="plant-<%= plant.id %>">
            <%= plant.name %>
            <!-- I cannot figure out how to pass the info I need to the controller -->
            <%= button_to "Remove Plant", plant_plot_path(plant_plot.id), method: :delete %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>